package main

import (
	"fmt"
	"math/rand"
	"net/http"
	"strings"
	"time"
)

func main() {

	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	for i := 0; i < 3; i++ {
		time.Sleep(1 * time.Second)
		r := rand.Intn(10)
		body := strings.NewReader(`{"TestID":` + fmt.Sprint(r) + `, "Interval": ` + fmt.Sprint(r) + `}`)
		req, err := http.NewRequest("POST", "http://localhost:9093/schedule", body)
		if err != nil {
			// handle err
		}
		req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			// handle err
		}
		defer resp.Body.Close()
	}

}
