# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntinel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='log',
            field=models.CharField(default='', max_length=65536),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='successful',
            field=models.NullBooleanField(),
        ),
    ]
